import random
import pyttsx3
import datetime
first_name = "Aayan"
last_name = "Singh Yadav"
gender = "male"
email = "NULL"
phone = "NULL"
gender = "male"
email = "NULL"
phone = "NULL"

bot_name = ""
bot_nickname = ""
version = "v2.5S"
username = "admin"
password = "admin"
fname = str(first_name)+ " " + str(last_name)


details = {    
    "FIRST NAME:": first_name,
    "LAST NAME:": last_name,
    "GENDER:": gender,
    "EMAIL:": email,
    "CONTACT:": phone,
    "USERNAME:": username,
    "PASSWORD:": "********"

    }

    # Call the get_current_time function to get the formatted time
if gender == "male":
    dust = str("sir")
elif gender == "female":
    dust = str("mam")
else:
    print("Unknown gender")

book = [
    "Rich Dad Poor Dad by Robert Kiyosaki",
    "The 7 Habits of Highly Effective People by Stephen R. Covey",
    "Atomic Habits by James Clear",
    "How to Win Friends and Influence People by Dale Carnegie",
    "Thinking, Fast and Slow by Daniel Kahneman",
    "The Power of Habit by Charles Duhigg",
    "Mindset: The New Psychology of Success by Carol S. Dweck",
    "Start with Why by Simon Sinek",
    "Sapiens: A Brief History of Humankind by Yuval Noah Harari",
    "The Subtle Art of Not Giving a F*ck by Mark Manson",
    "The Four Agreements by Don Miguel Ruiz",
    "The Lean Startup by Eric Ries",
    "Man's Search for Meaning by Viktor E. Frankl",
    "The Art of War by Sun Tzu",
    "Zero to One by Peter Thiel and Blake Masters",
    "Good to Great by Jim Collins",
    "The 48 Laws of Power by Robert Greene",
    "The Alchemist by Paulo Coelho",
    "Outliers by Malcolm Gladwell",
    "The Tipping Point by Malcolm Gladwell",
    "Deep Work by Cal Newport",
    "Essentialism: The Disciplined Pursuit of Less by Greg McKeown",
    "Grit: The Power of Passion and Perseverance by Angela Duckworth",
    "The Innovator's Dilemma by Clayton M. Christensen",
    "Drive: The Surprising Truth About What Motivates Us by Daniel H. Pink",
    "Quiet: The Power of Introverts in a World That Can't Stop Talking by Susan Cain",
    "Mindset: The New Psychology of Success by Carol S. Dweck",
    "The 5 Second Rule by Mel Robbins",
    "The One Thing by Gary Keller and Jay Papasan",
    "Deep Work by Cal Newport",
    "The Miracle Morning by Hal Elrod",
    "The Code of the Extraordinary Mind by Vishen Lakhiani",
    "Ego is the Enemy by Ryan Holiday",
    "Meditations by Marcus Aurelius",
    "The 80/20 Principle by Richard Koch",
    "The Compound Effect by Darren Hardy",
    "The Millionaire Next Door by Thomas J. Stanley and William D. Danko",
    "The 4-Hour Workweek by Timothy Ferriss",
    "The Intelligent Investor by Benjamin Graham",
    "Your Money or Your Life by Vicki Robin and Joe Dominguez",
    "I Will Teach You to Be Rich by Ramit Sethi",
    "The Total Money Makeover by Dave Ramsey",
    "Thinking in Bets by Annie Duke",
    "Daring Greatly by Brené Brown",
    "Leaders Eat Last by Simon Sinek",
    "The Gifts of Imperfection by Brené Brown",
    "The Obstacle is the Way by Ryan Holiday",
    "The 10X Rule by Grant Cardone",
    "Extreme Ownership by Jocko Willink and Leif Babin",
    "Can't Hurt Me by David Goggins"
]

booknname = random.choice(list(book))

conversation = {
  "/info": details,
  "hello": "Hello " + str(first_name) + dust + ", how can i assist you today?",
  "hi": "Hello " + str(first_name) + dust +", how can i assist you today?",
  "yo": "Hello " + str(first_name) + dust + ", how can i assist you today?",
  "what is my name": "YOUR NAME IS " + str(fname) + ", AM I  RIGHT " + str(dust),
  "how are you": "I'm doing well, thank you. what about you?",
  "what is your name": "My name is" + str(bot_nickname) + "How can I assist you today?",
  "what can you do": "I can answer any questions you have or provide assistance. Just let me know what you need!",
  "thank you": "You're welcome! Is there anything else I can help you with?",
  "bye": "Goodbye! Have a great day.",
  "what is the weather like today": "I'm sorry, I don't have access to real-time weather information. Is there anything else I can help you with?",
  "how old are you": "I AM JUST 10 YEARS OLD",
  "what do you like to do": "I like to help people and have conversations like this one.",
  "tell me a joke": "I'm sorry, I don't know any jokes.",
  "what is your favorite color": "I don't have a favorite color.",
  "what is the meaning of life": "I don't know the meaning of life.",
  "can you recommend a good book": "Sure, I recommend the book: " + str(booknname),
  "/book" : "Sure, I recommend the book: " + str(booknname),
  "what is the capital of France": "The capital of France is Paris.",
  "can you play a game with me": "I'm sorry, I don't know how to play any games.",
  "what is your favorite food": "I don't have a favorite food.",
  "what is the time now": "I'm sorry, I don't have access to the current time.",
  "what is your favorite music": "I don't have a favorite music genre.",
  "what is your favorite movie": "I don't have a favorite movie.",
  "can you sing a song": "I'm sorry, I can't sing.",
  "who are you": "I am a virtual assistant.",
  "what is a cell": "A cell is the basic unit of life. It is the smallest unit that can carry on the functions of life.",
  "what is a virus": "A virus is a non-living particle that can infect cells. Viruses can cause diseases, such as the common cold and the flu.",
  "what is an atom": "An atom is the smallest unit of an element. It is made up of protons, neutrons, and electrons.",
  "what is a molecule": "A molecule is two or more atoms that are chemically bonded together.",
  "what is a compound": "A compound is a substance that is made up of two or more elements that are chemically bonded together.",
  "what is a mixture": "A mixture is a substance that is made up of two or more elements or compounds that are not chemically bonded together.",
  "what is a solution": "A solution is a mixture that is made up of a solute and a solvent. The solute is the substance that is dissolved in the solvent.",
  "what is a suspension": "A suspension is a mixture that is made up of a solid that is suspended in a liquid. The solid particles will eventually settle to the bottom of the liquid.",
  "what is an emulsion": "An emulsion is a mixture that is made up of two or more liquids that are not normally miscible. Emulsions are stabilized by an emulsifier.",
  "what is a colloid": "A colloid is a mixture that is made up of a dispersed phase and a dispersion medium. The dispersed phase is the substance that is dispersed in the dispersion medium.",
  "what is a gas": "A gas is a state of matter that has no definite shape or volume. Gases are made up of molecules that are very far apart from each other.",
  "what is a liquid": "A liquid is a state of matter that has a definite volume but no definite shape. Liquids are made up of molecules that are close together but not touching.",
  "what is a solid": "A solid is a state of matter that has a definite shape and volume. Solids are made up of molecules that are very close together and touching.",
  "what is a chemical reaction": "A chemical reaction is a process in which one or more substances are changed into one or more new substances.",
  "what is an equation": "An equation is a mathematical statement that shows two expressions are equal.",
  "what is a balanced equation": "A balanced equation is an equation in which the number of atoms of each element is the same on both sides of the equation.",
  "what is a reactant": "A reactant is a substance that is present at the start of a chemical reaction.",
  "what is a product": "A product is a substance that is formed at the end of a chemical reaction.",
  "what is a precipitate": "A precipitate is a solid that forms when two liquids are mixed together.",
  "what is a gas evolution reaction": "A gas evolution reaction is a chemical reaction in which a gas is formed.",
  "what is a neutralization reaction": "A neutralization reaction is a chemical reaction in which an acid and a base react to form a salt and water.",
  "what is an oxidation-reduction reaction": "An oxidation-reduction reaction is a chemical reaction in which one substance is oxidized and another substance is reduced.",
  "what is an exothermic reaction": "An exothermic reaction is a chemical reaction that releases heat.",
  "what is an endothermic reaction": "An endothermic reaction is a chemical reaction that absorbs heat.",
  "what is a catalyst": "A catalyst is a substance that speeds up a chemical reaction without being consumed by the reaction.",
  "what is a buffer": "A buffer is a solution that resists changes in pH.",
  "what is a concentration": "Concentration is a measure of the amount of solute in a solution.",
  "what is a solution equilibrium": "A solution equilibrium is a state of balance in which the rate of the forward reaction is equal to the rate of the reverse reaction.",
  "what is a heterogeneous equilibrium": "A heterogeneous equilibrium is an equilibrium in which the reactants and products are in different phases.",
  "what is a homogeneous equilibrium": "A homogeneous equilibrium is an equilibrium in which the reactants and products are in the same phase.",
  "what is a chemical equilibrium": "A chemical equilibrium is an equilibrium in which the reactants and products are in a state of balance.",
  "what is the capital of Italy": "Rome, Italy.",
  "what is the capital of Germany": "Berlin, Germany.",
  "what is the capital of Russia": "Moscow, Russia.",
  "what is the capital of China": "Beijing, China.",
  "what is the capital of Japan": "Tokyo, Japan.",
  "what is the capital of India": "New Delhi, India.",
  "what is the capital of Brazil": "Brasilia, Brazil",
  "what is the capital of the United Kingdom": "London, United Kingdom",
  "what is the capital of Canada": "Ottawa, Canada",
  "what is the capital of Australia": "Canberra, Australia",
  "what is the capital of South Africa": "Pretoria, South Africa",
  "what is the capital of Mexico": "Mexico City, Mexico",
  "what is the capital of Argentina": "Buenos Aires, Argentina",
  "what is the capital of Egypt": "Cairo, Egypt",
  "what is the capital of Turkey": "Ankara, Turkey",
  "what is the capital of Iran": "Tehran, Iran",
  "what is the capital of Saudi Arabia": "Riyadh, Saudi Arabia",
  "what is the capital of Iraq": "Baghdad, Iraq",
  "what is the capital of Afghanistan": "Kabul, Afghanistan",
  "what is the capital of Pakistan": "Islamabad, Pakistan",
  "what is the capital of Nepal": "Kathmandu, Nepal",
  "what is the capital of Sri Lanka": "Colombo, Sri Lanka",
  "what is the capital of Myanmar": "Nay Pyi Taw, Myanmar",
  "what is the capital of Laos": "Vientiane, Laos",
  "what is the capital of Cambodia": "Phnom Penh, Cambodia",
  "what is the capital of Vietnam": "Hanoi, Vietnam",
  "what is the capital of Thailand": "Bangkok, Thailand",
  "what is the capital of Singapore": "Singapore, Singapore",
  "what is the capital of Malaysia": "Kuala Lumpur, Malaysia",
  "what is the capital of Indonesia": "Jakarta, Indonesia",
  "what is the capital of the Philippines": "Manila, Philippines",
  "who is this": "This is advance chat bot, designed by Aayan singh yadav",
  "fuck you": "sorry sir i did something wrong then please tell me",
  "fuck off": "sorry sir i am always here to help you",
    "hello, how are you": "I'm good, thank you. How about you",
    "where are you from": "I'm from New York. And you",
    "what do you do for a living": "I'm a software engineer. What about you",
    "do you have any hobbies": "Yes, I love reading and hiking. How about you",
    "what's your favorite book": "I love 'To Kill a Mockingbird'. Have you read it",
    "have you traveled recently": "Yes, I just came back from a trip to Spain. How about you",
    "what's your favorite cuisine": "I love Italian food. What's yours",
    "do you like sports": "Yes, I enjoy playing tennis. Do you play any sports",
    "what's your favorite movie": "I love 'The Shawshank Redemption'. Have you seen it",
    "do you have any pets": "Yes, I have a dog. Do you have any pets",
    "what's your favorite color": "Blue is my favorite color. What's yours",
    "do you like music": "Yes, I love listening to rock music. What about you",
    "who's your favorite artist": "I'm a big fan of The Beatles. How about you",
    "do you like to cook": "Yes, I enjoy cooking. Do you like to cook",
    "what's your favorite season": "I love spring. What about you",
    "do you have any siblings": "Yes, I have a brother. Do you have any siblings",
    "what's your favorite city": "I love Paris. Have you been there",
    "do you like to read": "Yes, I love reading. Do you",
    "what's your favorite holiday": "I love Christmas. What's your favorite holiday",
    "do you like coffee or tea": "I'm a coffee person. How about you",
    "what's your dream job": "I've always wanted to be a writer. What's yours",
    "do you prefer city or countryside": "I prefer the countryside for its tranquility. How about you",
    "what's your favorite type of music": "I enjoy classical music. What's your favorite",
    "do you have a favorite quote": "One of my favorites is 'Carpe Diem'. Do you have a favorite quote",
    "do you enjoy outdoor activities": "Yes, I love hiking and camping. How about you",
    "what's your favorite type of cuisine": "I love Mexican food. What about you",
    "do you have a favorite author": "I'm a big fan of J.K. Rowling. How about you",
    "do you like to travel": "Yes, I love exploring new places. Do you",
    "what's your favorite sport": "I enjoy watching football. What's your favorite sport",
    "do you have a favorite actor or actress": "I admire Meryl Streep's work. How about you",
    "do you like to garden": "Yes, I find it very relaxing. Do you",
    "what's your favorite flower": "I love roses. What's your favorite flower",
    "do you like to paint or draw": "I enjoy drawing in my free time. How about you",
    "what's your favorite museum": "I love the Louvre in Paris. Have you been there",
    "do you like to dance": "Yes, I enjoy salsa dancing. Do you",
    "what's your favorite animal": "I love dogs. What's your favorite animal",
    "do you like to bake": "Yes, I love making cookies. Do you",
    "what's your favorite board game": "I enjoy playing chess. What's your favorite",
    "do you like to swim": "Yes, I find it very refreshing. Do you",
    "what's your favorite fruit": "I love strawberries. What's your favorite fruit",
    "do you like to sing": "Yes, I enjoy singing in the shower. Do you",
    "who r u":"I am a virtual assistant.",
    "how r u":"I AM FINE SIR WHAT ABOUT YOU",
    "i knew it":"hehe",
    "what's your favorite dessert": "I love chocolate cake. What's your favorite dessert",
    "do you like to write": "Yes, I enjoy writing short stories. Do you",
    "what's your favorite beach": "I love Bondi Beach in Australia. Have you been there",
    "do you like to ski or snowboard": "I enjoy skiing. How about you",
    "what's your favorite planet": "I'm fascinated by Mars. What's your favorite planet",
    "do you like to take photos": "Yes, I love photography. Do you",
    "what's your favorite gemstone": "I love diamonds. What's your favorite gemstone",
    "do you like to knit or crochet": "I enjoy knitting in my free time. How about you",
    "what's your favorite constellation": "I love Orion. What's your favorite constellation",
    "do you like to run or jog": "I enjoy running in the morning. How about you",
    "are you a hacker":"No i am just a virtual assistant",
}

added_conversation = {
    "goodnight": "goodnight sweetdreams",
    "haha": "sir are you laughing?",
    "hmm": "sir what you're looking for",
    }